version: '3.8'

services:
  backend_dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mariadb
      - DB_USER=admin
      - DB_PASSWORD=dev_password
      - DB_NAME=CroW_dev
    depends_on:
      - mariadb
    networks:
      - dev_network

  mobile_dev:
    build:
      context: ./mobile
      dockerfile: Dockerfile.dev
    volumes:
      - ./mobile:/app
      - flutter_deps:/root/.pub-cache
    ports:
      - "8080:8080"
      - "35729:35729"
    environment:
      - BACKEND_URL=http://backend_dev:3000
    depends_on:
      - backend_dev
    networks:
      - dev_network

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: CroW_dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: dev_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_dev_data:/var/lib/mysql
    networks:
      - dev_network

volumes:
  mariadb_dev_data:
  flutter_deps:

networks:
  dev_network:
    driver: bridge
