name: crow_mobile
description: CroW Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_fonts: ^5.1.0
  animations: ^2.0.8
  
  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  fl_chart: ^0.69.2
  
  # État
  provider: ^6.1.2
  flutter_riverpod: ^2.4.9
  
  # Stockage local
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Réseau
  http: ^1.1.0
  dio: ^5.0.0
  connectivity_plus: ^6.1.0
  
  # Utilitaires
  intl: ^0.19.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  logger: ^1.1.0
  url_launcher: ^6.2.2
  package_info_plus: ^8.1.1
  
  # Authentification
  jwt_decoder: ^2.0.1
  local_auth: ^2.1.7
  # Localisation
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting et analyse statique
  flutter_lints: ^2.0.0
  custom_lint: ^0.7.0
  
  # Tests
  mockito: ^5.4.4
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  
  # Outils de développement
  flutter_native_splash: ^2.3.8
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/fr.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  generate: true

# Configuration des icônes de l'application
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

# Configuration du splash screen
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash_android12.png
    color: "#FFFFFF"